### ISSUE TITLE
ActivationBanner class should not throw a fatal error

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give-Addon-Boilerplate#26]
## User Story

When I have the Core plugin activated and my add-on using the boilerplate I receive:

```
( ! ) Fatal error: Uncaught Error: Class 'Give_Addon_Activation_Banner' not found in /Users/devinwalker/Local Sites/givetest/app/public/wp-content/plugins/give-double-the-donation/src/Addon/ActivationBanner.php on line 31
```

## Details

When I deactivated all other add-ons besides the one I created with the boilerplate and GiveWP Core I received the fatal error:

![2020-10-20_12-28-23](https://user-images.githubusercontent.com/1571635/96634735-c7875f00-12cf-11eb-824f-30376e88ec24.png)

## Expected Behavior

No fatal error occurs.

## Acceptance Criteria

-   [x] The ActivationBanner does not cause a fatal error in the boilerplate.

**Comment by JasonTheAdams** [comment]
@alaca It's not higher priority than anything you're currently working on, but when you have a chance please take care of this.
